### ISSUE TITLE
Long Method - Classe ATM24H

### ISSUE THREAD

**Issue by tallesb** [TPII20152/BankSys04#12]
Foi encontrado um Long Method na classe ATM24H. Resolva!

*Após a fixação dessa issue, printe o analizador XRay para verificar evolução.

**Comment by LizCardoso** [comment]
Mesmo depois das atualizações ainda está detectando bad smell, mas acredito que a classe já esteja ok! Separei o máximo possível e tirei a "regra de negocio" (tary/catch) que esta vá dentro do case! Vocês acham que essa issues já pode ser fechada? Deixem sugestões! @tallesb @lincolnrocha @LucasHF

**Comment by LucasHF** [comment]
Pelo que vi, os trechos de try/catch são semelhantes, mas cada um executa uma função diferente, então acredito que a Issue possa ser fechada.

**Comment by tallesb** [comment]
@LizCardoso, fecha logo isso. Resolveu? Então tá resolvido.
:trollface:
