### ISSUE TITLE
Long Method - Classe AccountController

### ISSUE THREAD

**Issue by tallesb** [TPII20152/BankSys04#13]
Foi encontrado um Long Method na classe AccountController.
Observamos algumas linhas de código repetidas.

*Após a fixação dessa issue, printe o analizador XRay para verificar evolução.

**Comment by LucasHF** [comment]
Ainda restou um Bad Smell, mas não é erro. Se modificar o código como o JDeodorant sugere podem ocorrer erros futuramente.
