### ISSUE TITLE
Type Checking - Classe AccountController

### ISSUE THREAD

**Issue by tallesb** [TPII20152/BankSys04#14]
Na classe AccountController temos um problema relacionado ao typedef. 

*Utilizar JDeodorant para localizar essa bad smell.
*Após a fixação dessa issue, printe o analizador XRay para verificar evolução.

**Comment by LucasHF** [comment]
Não foi necessário tratar o Bad Smell por não se tratar de um erro e sim uma verificação necessária para o funcionamento do código.
