### ISSUE TITLE
Casos de teste - Classe AccountVector

### ISSUE THREAD

**Issue by tallesb** [TPII20152/BankSys04#6]
Desenvolver casos de teste Classe AccountVector localizada no package banksys.persistence utilizando JUnit.

**Comment by tallesb** [comment]
Comit relacionado:
fc39458f3aadacbcec466b55a9f1b64b244ab003

Fechado

**Comment by LucasHF** [comment]
Porque foi feito o teste do método Retrieve() sem testar o FindAccount() já que o primeiro utiliza o segundo?
